
import { Promotion } from './types';

// HƯỚNG DẪN CẬP NHẬT (DÙNG CÔNG THỨC EXCEL CHO DANH SÁCH CHƯƠNG TRÌNH):
// Thứ tự các cột trong Excel của bạn:
// A: STT | B: Brand | C: Type (Activation/AWO) | D: Title | E: Region (Dữ liệu: GHCM, NO, CE, MKD) 
// F: Start Date | G: End Date | H: PC Image Link 
// I: Mobile Image Link | J: Venue List Link (AWO only) | K: Content
//
// CÔNG THỨC CHỐNG LỖI XUỐNG DÒNG (Dán vào cột L):
// ="{ id: 'promo-" & TEXT(F2,"yymmdd") & "-r" & ROW() & "', title: '" & SUBSTITUTE(SUBSTITUTE(D2, CHAR(10), " "), "'", "\'") & "', brand: '" & B2 & "', type: '" & C2 & "', regions: ['" & E2 & "'], cities: [], startDate: '" & TEXT(F2,"yyyy-mm-dd") & "', endDate: '" & TEXT(G2,"yyyy-mm-dd") & "', image: '" & H2 & "', mobileImage: '" & I2 & "', bu: '" & E2 & "', venueListLink: '" & J2 & "', content: '" & SUBSTITUTE(SUBSTITUTE(K2, CHAR(10), "\n"), "'", "\'") & "' },"

export const PROMOTION_DATA: Promotion[] = [
// Fixed: Split comma-separated regions into proper Region[] arrays to satisfy the type definition
{ id: 'promo-251201-r4', title: 'Tiger Festive - Săn Lộc Bản Lĩnh', brand: 'Tiger', type: 'Activation', regions: ['GHCM', 'NO', 'CE', 'MKD'], cities: [], startDate: '2025-12-01', endDate: '2026-03-31', image: 'https://i.postimg.cc/mrsqG386/Cover_ngang.jpg', mobileImage: 'https://i.postimg.cc/1tWY6kPK/Cover_doc.jpg', bu: 'GHCM,NO,CE,MKD', venueListLink: 'N/A', content: 'Mùa Tết năm nay, Tiger mang đến một hành trình hoàn toàn mới:\n “ĐÁNH THỨC BẢN LĨNH – SĂN LỘC KHAI XUÂN.”\n \n Tại Điểm Hẹn Săn Lộc, các mãnh hổ sẽ được mở khóa hàng loạt trải nghiệm đậm tinh thần Tết, đậm màu sắc Tiger!\n Hôm nay, Tiger không chỉ chúc lộc,\n Tiger trao lộc.\n Tiger khơi dậy lộc từ chính bản lĩnh của các mãnh hổ.' },
{ id: 'promo-251201-r5', title: 'Heineken Festive - Mở kết nối thật, Tết bật Heineken', brand: 'Heineken', type: 'Activation', regions: ['GHCM', 'NO', 'CE', 'MKD'], cities: [], startDate: '2025-12-01', endDate: '2026-03-31', image: 'https://i.postimg.cc/SNgyCFNS/1920x1080-1920x1080.jpg', mobileImage: 'https://i.postimg.cc/PxnhTdKF/1920x1080-1080x1920.jpg', bu: 'GHCM,NO,CE,MKD', venueListLink: 'N/A', content: 'MỞ KẾT NỐI THẬT – TẾT BẬT HEINEKEN\n\nTết đang đến gần — thời khắc để gác lại những “tín hiệu ảo”, cùng bật cảm xúc thật bên người thân và bạn bè.\nHeineken mời bạn đến điểm hẹn của những kết nối thật, nơi âm nhạc, niềm vui và những ly bia mát lạnh hòa cùng không khí rộn ràng cuối năm\n\n• Order 6 lon / chai Heineken bất kỳ → nhận 1 lượt chơi game TRÚNG QUÀ 100% (Túi tole, Bình Giữ nhiệt, Áo Polo, Gifbox Alu…)\n\n• Và cứ mỗi combo 6 Heineken → nhận ngay 1 vòng tay may mắn để tham gia Lucky Draw với các phần thưởng giá trị như: \n   Giải Nhất: Tai nghe Bluetooth Apple AirPods 4\n   Giải Đặc Biệt: Loa Heineken Marshall Action III\n\nHãy cùng mở kết nối thật   – bật niềm vui và khui mùa Tết thật đáng nhớ cùng Heineken! 🍻' },
{ id: 'promo-251208-r8', title: 'Larue Festive - Đón Điều Mới - Mở Tết Tấn Tới', brand: 'Larue', type: 'Activation', regions: ['MKD', 'CE'], cities: [], startDate: '2025-12-08', endDate: '2026-02-08', image: 'https://i.postimg.cc/9FQ2W8Pv/Banner-1920x1080.jpg', mobileImage: 'https://i.postimg.cc/gJp91NkD/Anh-mobile.jpg', bu: 'MKD,CE', venueListLink: 'N/A', content: 'CƠ HỘI ĐÓN ĐIỀU MỚI, TẤN TỚI NĂM BÍNH NGỌ 2026 CÙNG LARUE\nCả nhà ơi, hòa mình vào bầu không khí rộn ràng những ngày cuối năm và “khởi động” tinh thần lạc quan, tích cực cho các anh em trước thềm Tết 2026.\n🎉 Đêm tiệc “ĐÓN ĐIỀU MỚI – MỞ TẾT TẤN TỚI” mang đến loạt trải nghiệm náo nhiệt – quà tặng cực xịn – và những màn trình diễn bùng nổ mở đầu cho một mùa Tết thật may mắn. Cùng nhau mở khóa những điều mới mẻ và nhận lộc Tết từ Larue nha anh em!\n\n🎁 100% TRÚNG QUÀ – 1000% VUI HẾT MÌNH\n\nMột đêm duy nhất với không khí rộn ràng, quà tặng bùng nổ, mở lối cho một năm mới đủ đầy từ SỰ NGHIỆP - TÌNH DUYÊN - TÀI LỘC & SỨC KHOẺ\n🔥 Cách tham gia nhận quà:\n\n• Order 6 chai Larue bất kỳ → nhận 1 lượt chơi game TRÚNG QUÀ 100% (Nón, Bật lửa, Túi đeo chéo, Hộp quà Tết Đặc biệt…)\n\n• Và cứ mỗi combo 6 Larue → nhận ngay 1 phiếu rút thăm may mắn để tham gia Lucky Draw với các phần quà giá trị và cực kì hấp dẫn như: Smart Tivi 43 inch, Máy ép chậm, Thùng bia Larue Smooth\n\n✨ Hẹn anh em một đêm thật náo nhiệt để cùng Larue ĐÓN ĐIỀU MỚI - MỞ TẾT TẤN TỚI nhaaaa' },
{ id: 'promo-251218-r9', title: 'Bia Việt Festive Activation - Lời Cảm Ơn Chân Thành', brand: 'Bia Việt', type: 'Activation', regions: ['GHCM'], cities: [], startDate: '2025-12-18', endDate: '2026-01-31', image: 'https://i.postimg.cc/xCphjxFL/16-9-2-(Update).png', mobileImage: 'https://i.postimg.cc/W11G8Wfy/Bia-Viet-Festive-Loi-Cam-On-Chan-Thanh.png', bu: 'SE,SW', venueListLink: 'N/A', content: 'Cuối năm là lúc nâng ly Bia Việt để nói lời CẢM ƠN CHÂN THÀNH tới những người đã kề vai sát cánh suốt một năm qua. \nĐêm tiệc “CẢM ƠN CHÂN THÀNH” cùng Bia Việt chính là lời tri ân - hứa hẹn một đêm bia ngon, quà chất, vui cháy hết mình\nThời gian diễn ra từ 17h đến 21h tại các khu vực HCM, Tây Ninh, Đồng Nai.\n🍻 Bia Việt mát lạnh hết nấc\n🎵 Không khí rộn ràng, game cháy hết mình\n🎁 Quà tặng mang về đầy tay - cảm ơn anh em thật đậm sâu\n\n🎊Một đêm duy nhất để anh em quây quần, cụng ly và nhận quà đặc biệt từ Bia Việt:\n• Order combo 6 lon/chai Bia Việt bất kỳ → nhận 1 lượt chơi game tại bàn hoặc 1 lượt hái lộc có cơ hội nhận những phần quà hấp dẫn: Bộ ly festive 2026, túi du lịch Bia Việt, bật lửa Bia Việt, áo mưa Bia Việt\n• Với combo 6 lon/chai → nhận ngay phiếu bốc thăm may mắn với nhiều phần quà giá trị: loa Karaoke (SW), quạt điều hòa (SE), giỏ quà tết 2026, bếp điện từ' },
{ id: 'promo-251210-r10', title: 'Bivina Festive - Bến Đầy Lộc', brand: 'Bivina', type: 'Activation', regions: ['CE', 'MKD'], cities: [], startDate: '2025-12-10', endDate: '2026-02-07', image: 'https://i.postimg.cc/LsdGZNf5/BIVINA-banner-web-pc.jpg', mobileImage: 'https://i.postimg.cc/jdVDjJd6/BIVINA-Kv-web-mobile-(1).png', bu: 'CE,MKD', venueListLink: '', content: 'Mùa Tết năm nay, Bivina mang đến một diện mạo mới với hình ảnh "BẾN ĐẦY LỘC" - một nơi chứng kiến và chào đón anh em sau một hành trình làm việc kiên trì với những thành quả xứng đáng. Khi thấy Hải Đăng tại Bến là thấy Lộc. \nTại Bến Đầy Lộc của Bivina anh em sẽ cùng nhau trải nghiệm, kết nối với nhau và mang về "ê hề" lộc với 3 loại lộc : Lộc Vững Vàng, Lộc Bình An, Lộc Bội Thu (MKD)/Đầy Khoang (Central)\nLoại hình hoạt động: Basic scale & roving scale\n🔥 Cách tham gia nhận quà:\n🎁 Lộc Vững vàng: \n• Order 6 lon/chai Bivina → nhận 1 lượt chơi game TRÚNG QUÀ 100% (Áo thun Bivina, Bình nước 1,6L Bivina, Áo mưa Bivina,  Nón Bivina, Hộp quà 3 ly Bivina) (quy định 1 phần quà/bàn/đêm)\n•Và cứ mỗi combo 6 lon/chai Bivina → nhận ngay 1 Phiếu rút thăm trúng thưởng  để tham gia Lucky Draw với các phần thưởng giá trị như: (1 Giải nhất) 1 vali kéo Bivina, ( 2 Giair nhì) túi du lịch Bivina + 1 thùng bia Bivina \n 🎊Lộc Bình An: Hái lộc trên cây mai Bivina (theo outlet) để nhận về các lộc may mắn đầu năm như: 15 câu chúc từ Bivina, 10 lon bia Bivina và 5 ly thuỷ tinh \n 🍻  Lộc Bội Thu/đầy khoang: \n- Loto show với bộ hình ảnh loto cực độc đáo mới lạ . Giải thưởng : 2 thùng bia Bivina \n- Rút thăm trúng thưởng \n- Karaoke vinh danh tinh thần chất biển & đón lộc đầu năm (MKD)\n' },

{ id: 'promo-260101-r6', title: 'Tiger YEP GHCM - Lên Tiệc cùng Tiger', brand: 'Tiger', type: 'AWO', regions: ['GHCM'], cities: [], startDate: '2026-01-01', endDate: '2026-04-15', image: 'https://i.postimg.cc/YqvLV9WR/NEW-Banner-Gifbox-voucher-16-9.jpg', mobileImage: 'https://i.postimg.cc/9fMwZYh2/NEW-2Congratulations-Screen-16-01-26.jpg', bu: 'GHCM', venueListLink: 'https://www.google.com/maps/d/u/0/edit?mid=1Kh5u8bisrzv3OfukFC4gEakAH5I4wk0&usp=sharing', content: 'Thời gian diễn ra: 01/01/2026 – 15/04/2026\n  Phạm vi áp dụng: tại Tp. Hồ Chí Minh, Tây Ninh, Bình Dương, Bình Phước, Đồng Nai, Vũng Tàu\n Quà tặng từ chương trình: 1 Hộp quà Tết Tiger\n Đối tượng tham gia: \n - Mọi công dân đang sinh sống và làm việc tại Việt Nam từ đủ 18 tuổi trở lên, đáp ứng điều kiện đều có thể tham gia chương trình (Có đối chiếu CCCD khi nhận quà, không chụp hình).\n - Quà tặng dành cho các khách hàng có tiệc và sử dụng 2 thùng/két Tiger trong thời gian diễn ra chương trình.\n - Chương trình chỉ áp dụng tại các quán nằm trong danh sách áp dụng chương trình.\n - Khách hàng có tiệc chỉ được nhận tối đa 02 (hai) bộ quà/Bàn trong suốt thời gian diễn ra chương trình.' },
//{ id: 'promo-251219-r7', title: 'Heineken YEP - Săn tiệc cùng Heineken', brand: 'Heineken', type: 'AWO', regions: ['GHCM', 'MKD', 'CE', 'NO'], cities: [], startDate: '2025-12-19', endDate: '2026-02-08', image: '', mobileImage: '', bu: 'GHCM,MKD,CE,NO', venueListLink: 'https://www.google.com/maps/d/u/0/edit?mid=1JiKkJGZWGXf-jnhZI9l30gnj0lJBouc&usp=sharing', content: '100% NHẬN QUÀ – THƯỞNG THỨC NGAY 2 THÙNG HEINEKEN 🍻\nĐặt tiệc trước 12h trưa mỗi ngày và thưởng thức khoảnh khắc Khai Tiệc đẳng cấp cùng Bia sủi Độc Bản Heineken Brut Lager trong mùa lễ hội năm nay✨\n\n⏰ Thời gian áp dụng:\n• Thứ 4 – Thứ 7\n• 17h30 – 21h30\n• Từ 19/12/2025 – 07/02/2026\n\n📲 Quét QR để đặt tiệc ngay\n📞 Hotline: 0378 956 513\n\n⚠️ Số lượng quà có hạn – chương trình có thể kết thúc sớm khi hết quà.\n🔞 Người dưới 18 tuổi không được uống rượu bia.\n\n#Heineken #HeinekenBrutLager\n#KhaiTiecCungHeineken #100PhanTramTrungThuong\n#DatTiecNgay' },


];
